language: node_js
node_js:
  - "node"
  - "6"
install:
  - npm install -g typescript mocha
  - npm install
after_script:
  - npm run test-coverage
  - cat ./coverage/lcov.info | node ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  